### PR TITLE
Remove unused var and useless statement

### PR DESCRIPTION
**Pull request by pilou-**

### CODE REVIEW

**Comment by j00bar** [comment]
I'm fine with using `repr()` for using the quotes, however in the case that `tempfile.mkdtemp`is the exception being handled in `__exit__`, `self.temp_dir` won't be defined and the logging statement will raise an Exception.

**Comment by j00bar** [comment]
Thanks for the contribution!

**Comment by pilou-** [comment]
When an exception is raised by `__enter__` method, `__exit__` method isn't called: `__exit__` can not handle an exception raised by `tempfile.mkdtemp`.

**Comment by pilou-** [comment]
@j00bar is that ok with you ?

**Comment by j00bar** [comment]
+1 LGTM thanks!!

**Pull request merged**
