### PR TITLE
Update README.md with info on how to get involved

### PR DESCRIPTION
**Pull request by jfchevrette**
##### ISSUE TYPE
 - Docs Pull Request

##### SUMMARY
Was not immediately obvious that the #ansible-container channel existed. I figured it's probably not a bad idea to pull some of the _Get Involved_ info from ansible's README file and add it here.

I did not find ansible-container -specific mailing lists so I left them unchanged.

### CODE REVIEW

**Comment by chouseknecht** [comment]
@gregdek The intention of this PR is noble. However, it points users  and contributors to the Ansible mailing lists. Is that what we want, or should we set up a mailing list specific to Ansible Container?

**Comment by gregdek** [comment]
We have a new mailing list as of Friday, actually, so let's announce it. :)

https://groups.google.com/forum/?hl=en-GB#!forum/ansible-container

**Comment by chouseknecht** [comment]
I think we need something more like #157

**Comment by gregdek** [comment]
Sounds good to me. Let's go with #157.

**Comment by chouseknecht** [comment]
Closing in favor of #157.

**Pull request closed without merging**
