### PR TITLE
Adds var_file to settings in container.yml

### PR DESCRIPTION
**Pull request by chouseknecht**
##### ISSUE TYPE
 - Feature Pull Request

##### SUMMARY
- Adds `--vars-files` CLI option, with `--var-file` and `--vars-file` as aliases, to accept one or more variables files as parameters.
- Adds `vars_files` option to settings
- Adds doc updates for `--vars-files` and `settings.vars_files`

### CODE REVIEW

**Comment by ehelms** [comment]
Can you only pass/set a single var_file?

**Comment by chouseknecht** [comment]
@ehelms, yep. Not sure why, but it's limited to a single file: https://github.com/ansible/ansible-container/blob/develop/container/cli.py#L253

**Comment by ehelms** [comment]
This change looks good then. Might be worth filing an issue for someone to pickup to make this multi-valued in the future.

**Comment by chouseknecht** [comment]
I might expand it. Doesn't look that hard...

**Pull request merged**
