### PR TITLE
Fix pip 10 parse_requirements

### LINKED ISSUE #919: Support for pip 10 - breaking changes introduced.
- Bug Report
##### SUMMARY

Pip has now has reached stable version 10, which has breaking change causing 
ansible-container to fail during install

```
    from pip.req import parse_requirements
    ImportError: No module named req
```

##### STEPS TO REPRODUCE

Ensure you have latest stable pip 
```
  pip install -U pip
```

Try to install ansible-container

```
pip install ansible-container[docker]
```
##### EXPECTED RESULTS
ansible-container gets installed

##### ACTUAL RESULTS

Installation fails with stacktrace final lines:

```
    from pip.req import parse_requirements
    ImportError: No module named req
```

### PR DESCRIPTION
**Pull request by tobill**
##### ISSUE TYPE
 - Bugfix Pull Request

##### SUMMARY

Fixes #919 

```

```

### CODE REVIEW

**Comment by marcosdiez** [comment]
This works perfectly over here. You somebody else is having this problem (Ubuntu 16.04) for example, just install ansible-container like this: 

`pip install git+https://github.com/tobill/ansible-container.git@develop`

**Comment by cikupin** [comment]
need this PR to be merged into master in order to support pip 10 <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:30.0235017626322% 4.054054054054054%;background-size:5418.75% 5418.75%" data-codepoints="1f44d"></span></span>

**Review by marcusianlevine — APPROVED** [review]
The build is failing for what seems like an unrelated reason, but this at least gets the build further than where it currently fails on ansible/develop and gets `pip install` working

**Comment by marcusianlevine** [comment]
@chouseknecht @j00bar can we get this merged? We have three open PRs now addressing the same pip regression #926 #923 

We need to address the otherwise failing tests but `ansible:develop` doesn't even get past installation...

**Comment by gregdek** [comment]
Fixed by #939 instead. Thanks!

**Pull request closed without merging**
