### PR TITLE
Prebaked conductors, redux

### PR DESCRIPTION
**Pull request by ryansb**
##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY

Updated version of prebaking conductors onto current dev w/ some bugfixes. Currently `python setup.py prebake` bakes all images, but I've found some flakiness with Jessie builds.

### CODE REVIEW

**Comment by ryansb** [comment]
Specific Jessie error:

```
Building Docker Engine context...               
Starting Docker build of Ansible Container Conductor image (please be patient)...                
ERROR   Failure building prebaked image for debian:jessie                                        
Traceback (most recent call last):              
  File "/home/ryansb/code/ansible-container/container/core.py", line 136, in hostcmd_prebake     
    cache=cache)        
  File "/home/ryansb/code/ansible-container/container/docker/engine.py", line 104, in __wrapped__
    return fn(self, *args, **kwargs)            
  File "/home/ryansb/code/ansible-container/container/__init__.py", line 28, in __wrapped__      
    return fn(*args, **kwargs)                  
  File "/home/ryansb/code/ansible-container/container/docker/engine.py", line 1025, in build_conductor_image             
    nocache=not cache)  
  File "/home/ryansb/.pyenv/versions/ac/lib/python2.7/site-packages/docker/models/images.py", line 172, in build         
    raise BuildError(chunk['error'])            
BuildError: Get https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz: dial tcp: lookup get.docker.com: no such host
```

**Comment by TomasTomecek** [comment]
@ryansb what's the status here?

**Comment by fignew** [comment]
What is the ansible-container argument to disable this? I am running on ARM and the the pre-built images will not work.

**Comment by chouseknecht** [comment]
@fignew 

I don't see a `disable` option. The docs state that you can build your own: http://docs.ansible.com/ansible-container/conductor.html

Referencing the [template conductor Dockerfile](https://github.com/ansible/ansible-container/blob/develop/container/docker/templates/conductor-src-dockerfile.j2) provides a roadmap.

**Comment by chouseknecht** [comment]
@fignew 

I forgot... You can build a conductor locally using the following command:

```
$ python ./setup.py prebake --distros $BASE_DISTRO --debug
```

You can see a full example in our [.travis.yml](https://github.com/ansible/ansible-container/blob/develop/.travis.yml) file. You'll need to run Ansible Container from source, so that you have a local copy of the project and access to `setup.py`.

Replace `BASE_DISTRO` with `centos:7`, `ubuntu:precise`, or whatever distro:tag you're needing. 

Hope this helps.

**Pull request merged**
