### PR TITLE
Prevent errors when src is none

### PR DESCRIPTION
**Pull request by ehelms**
##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### SUMMARY

```

```

### CODE REVIEW

**Comment by ehelms** [comment]
Testing blocked by -- https://github.com/ansible/ansible-container/pull/870

**Comment by pilou-** [comment]
When applied on `devel`, I confirm this pull-request fixes the following exception (occur with a `copy` task without `src` parameter):
```
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 423, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 809, in conductorcmd_build
    role_fingerprint = get_role_fingerprint(role, service_name, config_vars)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 326, in get_role_fingerprint
    hash_role(hash_obj, resolve_role_to_path(role))
  File "/_ansible/container/utils/__init__.py", line 286, in hash_role
    hash_role(hash_obj, dependency_path)
  File "/_ansible/container/utils/__init__.py", line 286, in hash_role
    hash_role(hash_obj, dependency_path)
  File "/_ansible/container/utils/__init__.py", line 303, in hash_role
    if not os.path.exists(src) or not src.startswith(('/', '..')): continue
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by ehelms** [comment]
Thanks for testing @pilou- , this is now unblocked.

**Review by marcusianlevine — APPROVED** [review]
LGTM

**Comment by marcusianlevine** [comment]
@j00bar @chouseknecht anything preventing this from being merged?

**Pull request merged**
