### PR TITLE
travis-ci.com

### PR DESCRIPTION
**Pull request by gundalow**

### CODE REVIEW

**Comment by Voronenko** [comment]
Thanks for spotting
Let's wait for pipeline :)

**Comment by gundalow** [comment]
@Voronenko FYI I've migrated from old to new Travis and removed the old app.
I'll merge once green

**Comment by Voronenko** [comment]
If branch tests passed, what is  second set of tests
https://github.com/ansible/ansible-container/pull/974/checks?check_run_id=42898429

**Comment by gundalow** [comment]
@Voronenko It's because I created a branch in this repo.

**Pull request merged**
