### PR TITLE
Issue 253

### PR DESCRIPTION
**Pull request by dalethestirling**
##### ISSUE TYPE
- Bugfix Pull Request
##### SUMMARY

This pull request fixes issue 253

ansible-container shipit kube will now create ansible playbook instead of raising exception.

### CODE REVIEW

**Comment by chouseknecht** [comment]
@dalethestirling 

Thank you for your interest in Ansible Container, and a sincere thank-your for taking the time to work on this PR. 

Can you please rebase your feature branch, and I'll get this merged. 

Thanks!

**Comment by dalethestirling** [comment]
@chouseknecht rebase is complete

**Comment by j00bar** [comment]
How about just...

```
def _port_exists(port, ports):
    return int(port) in ports
```

**Comment by chouseknecht** [comment]
@dalethestirling tests are now working correctly, and it looks like you have a bug in kubernetes/deployment.py. If you make the change suggested by @j00bar, that will fix the error. 

Once that's fixed, I'll test this out, and then we'll merge it.

**Comment by dalethestirling** [comment]
@j00bar thanks for the review and advice 

@chouseknecht all good to go

**Comment by chouseknecht** [comment]
Replaced by #296. 

When building config files each port in the ports list is a dict, and when generating a role each port is an int. Therefore the code has to check the port variable's type before making the comparison.

**Pull request closed without merging**
