### PR TITLE
Add support for amazonlinux as a conductor container

### PR DESCRIPTION
**Pull request by winky**
When we want to use amazonlinux image that is based on centos, we can't use centos based conductor.
As the reason, the name of amazonlinux yum packages are different from centos.

##### ISSUE TYPE
 - Feature Pull Request

##### SUMMARY
This pull requests modifies the template conductor-dockerfile.j2
including a block that installs the necessary packages for a amazonlinux
container.

### CODE REVIEW

**Comment by j00bar** [comment]
Howdy! Thank you for the pull request! One more spot to get in `PREBAKED_DISTROS` in `container.docker.engine` and I think we'd be good to go.

**Comment by winky** [comment]
@j00bar 
Thank you for your comment. I add commit to change `PREBAKED_DISTROS`.
Please check changes.

**Comment by TomasTomecek** [comment]
@j00bar @chouseknecht can we merge?

**Comment by chouseknecht** [comment]
Seems OK to me. Ship it!

**Pull request merged**
